spring.application.name=career-network


cognodb.uri=${COGNODB_URI:bolt+s://db-a75f0f32.databases.cognodb.com}
cognodb.username=${COGNODB_USERNAME:cognodb}
cognodb.password=${COGNODB_PASSWORD:67e5de127386f0d6f11c2c394f3f548b}

# Load the seed dataset on startup only when the database is empty
careernetwork.seed.enabled=true
