// Seed data for the Career Network graph.
// Run automatically on startup by SeedDataLoader, only when the database is empty.
// Model: (:Person)-[:WORKS_AT]->(:Company), (:Person)-[:HAS_SKILL]->(:Skill), (:Person)-[:KNOWS]-(:Person)

CREATE (p1:Person {id:'p1', name:'RamanaReddy', headline:'Backend Engineer', location:'Austin, TX', email:'RamanaReddy@example.com'})
CREATE (p2:Person {id:'p2', name:'Sreekanth', headline:'Frontend Engineer', location:'Seattle, WA', email:'Sreekanth@example.com'})
CREATE (p3:Person {id:'p3', name:'Vineetha', headline:'Data Scientist', location:'Austin, TX', email:'Vineetha@example.com'})
CREATE (p4:Person {id:'p4', name:'Aravind', headline:'Engineering Manager', location:'New York, NY', email:'Aravind@example.com'})
CREATE (p5:Person {id:'p5', name:'Afshad', headline:'Product Designer', location:'Seattle, WA', email:'Afshad@example.com'})
CREATE (p6:Person {id:'p6', name:'Yaswanth', headline:'DevOps Engineer', location:'Denver, CO', email:'Yaswanth@example.com'})
CREATE (p7:Person {id:'p7', name:'Kavya', headline:'Full-Stack Developer', location:'Austin, TX', email:'Kavya@example.com'})
CREATE (p8:Person {id:'p8', name:'Alekhya', headline:'Machine Learning Engineer', location:'Boston, MA', email:'Alekhya@example.com'})
CREATE (p9:Person {id:'p9', name:'Rajesh', headline:'Product Manager', location:'New York, NY', email:'Rajesh@example.com'})
CREATE (p10:Person {id:'p10', name:'Rahul', headline:'Backend Engineer', location:'Denver, CO', email:'Rahul@example.com'})
CREATE (p11:Person {id:'p11', name:'Lakshmi', headline:'QA Engineer', location:'Boston, MA', email:'Lakshmi@example.com'})
CREATE (p12:Person {id:'p12', name:'Ravi', headline:'Solutions Architect', location:'San Francisco, CA', email:'Ravi@example.com'})
CREATE (p13:Person {id:'p13', name:'Rajitha', headline:'Data Engineer', location:'San Francisco, CA', email:'Rajitha@example.com'})
CREATE (p14:Person {id:'p14', name:'Afsha', headline:'Frontend Engineer', location:'Austin, TX', email:'Afsha@example.com'})
CREATE (p15:Person {id:'p15', name:'Santhosh', headline:'Security Engineer', location:'Seattle, WA', email:'Santhosh@example.com'})
CREATE (p16:Person {id:'p16', name:'Rekha', headline:'Backend Engineer', location:'New York, NY', email:'Rekha@example.com'})
CREATE (p17:Person {id:'p17', name:'Seetha', headline:'Product Designer', location:'Denver, CO', email:'Seetha@example.com'})
CREATE (p18:Person {id:'p18', name:'Geetha', headline:'Data Scientist', location:'Boston, MA', email:'Geetha@example.com'})

CREATE (c1:Company {id:'c1', name:'Nimbus Cloud', industry:'Cloud Infrastructure'})
CREATE (c2:Company {id:'c2', name:'BrightPixel', industry:'Design Tools'})
CREATE (c3:Company {id:'c3', name:'Vector Analytics', industry:'Data & AI'})
CREATE (c4:Company {id:'c4', name:'Northwind Labs', industry:'DevTools'})
CREATE (c5:Company {id:'c5', name:'Harborline Systems', industry:'FinTech'})
CREATE (c6:Company {id:'c6', name:'Everly Health', industry:'HealthTech'})

CREATE (s1:Skill {name:'Java'})
CREATE (s2:Skill {name:'Spring Boot'})
CREATE (s3:Skill {name:'React'})
CREATE (s4:Skill {name:'TypeScript'})
CREATE (s5:Skill {name:'Python'})
CREATE (s6:Skill {name:'Machine Learning'})
CREATE (s7:Skill {name:'Cypher / Graph DBs'})
CREATE (s8:Skill {name:'Kubernetes'})
CREATE (s9:Skill {name:'Product Strategy'})
CREATE (s10:Skill {name:'UX Design'})
CREATE (s11:Skill {name:'SQL'})
CREATE (s12:Skill {name:'Security'})

CREATE (p1)-[:WORKS_AT {role:'Senior Backend Engineer', startYear:2021}]->(c1)
CREATE (p2)-[:WORKS_AT {role:'Frontend Engineer', startYear:2022}]->(c2)
CREATE (p3)-[:WORKS_AT {role:'Data Scientist', startYear:2020}]->(c3)
CREATE (p4)-[:WORKS_AT {role:'Engineering Manager', startYear:2019}]->(c1)
CREATE (p5)-[:WORKS_AT {role:'Product Designer', startYear:2021}]->(c2)
CREATE (p6)-[:WORKS_AT {role:'DevOps Engineer', startYear:2022}]->(c4)
CREATE (p7)-[:WORKS_AT {role:'Full-Stack Developer', startYear:2023}]->(c1)
CREATE (p8)-[:WORKS_AT {role:'ML Engineer', startYear:2020}]->(c3)
CREATE (p9)-[:WORKS_AT {role:'Product Manager', startYear:2018}]->(c5)
CREATE (p10)-[:WORKS_AT {role:'Backend Engineer', startYear:2022}]->(c4)
CREATE (p11)-[:WORKS_AT {role:'QA Engineer', startYear:2021}]->(c6)
CREATE (p12)-[:WORKS_AT {role:'Solutions Architect', startYear:2017}]->(c1)
CREATE (p13)-[:WORKS_AT {role:'Data Engineer', startYear:2021}]->(c3)
CREATE (p14)-[:WORKS_AT {role:'Frontend Engineer', startYear:2023}]->(c2)
CREATE (p15)-[:WORKS_AT {role:'Security Engineer', startYear:2020}]->(c5)
CREATE (p16)-[:WORKS_AT {role:'Backend Engineer', startYear:2019}]->(c5)
CREATE (p17)-[:WORKS_AT {role:'Product Designer', startYear:2022}]->(c6)
CREATE (p18)-[:WORKS_AT {role:'Data Scientist', startYear:2020}]->(c6)

CREATE (p1)-[:HAS_SKILL {level:'Expert'}]->(s1)
CREATE (p1)-[:HAS_SKILL {level:'Expert'}]->(s2)
CREATE (p1)-[:HAS_SKILL {level:'Intermediate'}]->(s7)
CREATE (p2)-[:HAS_SKILL {level:'Expert'}]->(s3)
CREATE (p2)-[:HAS_SKILL {level:'Expert'}]->(s4)
CREATE (p3)-[:HAS_SKILL {level:'Expert'}]->(s5)
CREATE (p3)-[:HAS_SKILL {level:'Expert'}]->(s6)
CREATE (p3)-[:HAS_SKILL {level:'Intermediate'}]->(s7)
CREATE (p4)-[:HAS_SKILL {level:'Expert'}]->(s1)
CREATE (p4)-[:HAS_SKILL {level:'Intermediate'}]->(s9)
CREATE (p5)-[:HAS_SKILL {level:'Expert'}]->(s10)
CREATE (p5)-[:HAS_SKILL {level:'Intermediate'}]->(s3)
CREATE (p6)-[:HAS_SKILL {level:'Expert'}]->(s8)
CREATE (p6)-[:HAS_SKILL {level:'Intermediate'}]->(s1)
CREATE (p7)-[:HAS_SKILL {level:'Expert'}]->(s1)
CREATE (p7)-[:HAS_SKILL {level:'Expert'}]->(s3)
CREATE (p7)-[:HAS_SKILL {level:'Intermediate'}]->(s2)
CREATE (p8)-[:HAS_SKILL {level:'Expert'}]->(s5)
CREATE (p8)-[:HAS_SKILL {level:'Expert'}]->(s6)
CREATE (p9)-[:HAS_SKILL {level:'Expert'}]->(s9)
CREATE (p10)-[:HAS_SKILL {level:'Expert'}]->(s1)
CREATE (p10)-[:HAS_SKILL {level:'Expert'}]->(s2)
CREATE (p10)-[:HAS_SKILL {level:'Intermediate'}]->(s11)
CREATE (p11)-[:HAS_SKILL {level:'Expert'}]->(s11)
CREATE (p12)-[:HAS_SKILL {level:'Expert'}]->(s7)
CREATE (p12)-[:HAS_SKILL {level:'Expert'}]->(s8)
CREATE (p13)-[:HAS_SKILL {level:'Expert'}]->(s5)
CREATE (p13)-[:HAS_SKILL {level:'Expert'}]->(s11)
CREATE (p13)-[:HAS_SKILL {level:'Intermediate'}]->(s7)
CREATE (p14)-[:HAS_SKILL {level:'Expert'}]->(s3)
CREATE (p14)-[:HAS_SKILL {level:'Expert'}]->(s4)
CREATE (p15)-[:HAS_SKILL {level:'Expert'}]->(s12)
CREATE (p15)-[:HAS_SKILL {level:'Intermediate'}]->(s8)
CREATE (p16)-[:HAS_SKILL {level:'Expert'}]->(s1)
CREATE (p16)-[:HAS_SKILL {level:'Intermediate'}]->(s11)
CREATE (p17)-[:HAS_SKILL {level:'Expert'}]->(s10)
CREATE (p18)-[:HAS_SKILL {level:'Expert'}]->(s5)
CREATE (p18)-[:HAS_SKILL {level:'Expert'}]->(s6)

CREATE (p1)-[:KNOWS {since:2021}]->(p4)
CREATE (p1)-[:KNOWS {since:2022}]->(p7)
CREATE (p1)-[:KNOWS {since:2022}]->(p6)
CREATE (p1)-[:KNOWS {since:2023}]->(p10)
CREATE (p2)-[:KNOWS {since:2022}]->(p5)
CREATE (p2)-[:KNOWS {since:2023}]->(p14)
CREATE (p3)-[:KNOWS {since:2020}]->(p8)
CREATE (p3)-[:KNOWS {since:2021}]->(p13)
CREATE (p3)-[:KNOWS {since:2022}]->(p18)
CREATE (p4)-[:KNOWS {since:2019}]->(p12)
CREATE (p4)-[:KNOWS {since:2021}]->(p9)
CREATE (p5)-[:KNOWS {since:2021}]->(p17)
CREATE (p6)-[:KNOWS {since:2022}]->(p10)
CREATE (p6)-[:KNOWS {since:2023}]->(p12)
CREATE (p7)-[:KNOWS {since:2023}]->(p14)
CREATE (p7)-[:KNOWS {since:2023}]->(p16)
CREATE (p8)-[:KNOWS {since:2021}]->(p18)
CREATE (p9)-[:KNOWS {since:2019}]->(p16)
CREATE (p9)-[:KNOWS {since:2020}]->(p15)
CREATE (p10)-[:KNOWS {since:2022}]->(p16)
CREATE (p11)-[:KNOWS {since:2021}]->(p17)
CREATE (p11)-[:KNOWS {since:2022}]->(p18)
CREATE (p12)-[:KNOWS {since:2018}]->(p1)
CREATE (p12)-[:KNOWS {since:2020}]->(p13)
CREATE (p13)-[:KNOWS {since:2022}]->(p3)
CREATE (p14)-[:KNOWS {since:2023}]->(p2)
CREATE (p15)-[:KNOWS {since:2021}]->(p6)
CREATE (p16)-[:KNOWS {since:2020}]->(p4)
CREATE (p17)-[:KNOWS {since:2022}]->(p9)
CREATE (p18)-[:KNOWS {since:2021}]->(p11)

